name: gantt_chart
description: A fully customizable gantt chart package written purely in dart
version: 0.2.0
homepage: https://github.com/Bdaya-Dev/flutter_gantt_chart

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: